### ISSUE TITLE
The hello demo doesn't work

### ISSUE THREAD

**Issue by marius851000** [stagedml/pylightnix#1]
Hello. The hello demo doesn't work, returning an error like 'PermissionError: [Errno 13] Permission denied: 'aclocal.m4''

This is due to (if I'm ok) the folder being Read-Only in the store, and then copied to the tempory folder for compilation, which is then read only.

I also have a diferent and probably more important problem with it: When I run the hello demo multiple time, I have the error 'FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pylightnix_hello_demo/2f56e6f987a1da0271915894ca19e28f-hello-src/config.json'
' I effectively doesn't have a folder named like that, but I have a context.json in one of it's subfolder.

**Comment by grwlf** [comment]
Hi. thanks for the report. I recently added read-only mode for storage and forget to rebuild demos. Now I think master has a solution for the 'Permission denied' part of the problem. Fixes are:
1) Core preserves executable bit when changing permission ro read-only
2) Hello realizer now has to set 'rw' mode back before work with the sources

'FileNotFound' part is not yet clear for me. File `config.json` normally should always exist in derivation folders like `/tmp/pylightnix_hello_demo/2f56e6f987a1da0271915894ca19e28f-hello-src/` (`context.json` is also a mandatory file, but I think it is unrelated here)

**Comment by grwlf** [comment]
Ok, second part now looks clear too. Turns out that `rmtree()` call can't delete reaonly folders, but the `config.json` turned out to be un-protected and it actually was deleted. So the storage was corrupted by `rmtree` in your case. I've posted a fix with a more powerful remover function. I'll also make `config.json` write-protected soon.

The demo should already work now, please check
